package com.sh.domain;
// Generated 2017-10-25 16:26:02 by Hibernate Tools 5.2.5.Final

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private String addId;
	private User user;
	private String name;
	private String address;
	private String phone;

	public Address() {
	}

	public Address(String addId) {
		this.addId = addId;
	}

	public Address(String addId, User user, String name, String address, String phone) {
		this.addId = addId;
		this.user = user;
		this.name = name;
		this.address = address;
		this.phone = phone;
	}

	public String getAddId() {
		return this.addId;
	}

	public void setAddId(String addId) {
		this.addId = addId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
