package com.sh.domain;
// Generated 2017-10-25 16:26:02 by Hibernate Tools 5.2.5.Final

/**
 * Orderitem generated by hbm2java
 */
public class Orderitem implements java.io.Serializable {

	private String itemid;
	private Orders orders;
	private Product product;
	private Integer count;
	private Double subtotal;

	public Orderitem() {
	}

	public Orderitem(String itemid) {
		this.itemid = itemid;
	}

	public Orderitem(String itemid, Orders orders, Product product, Integer count, Double subtotal) {
		this.itemid = itemid;
		this.orders = orders;
		this.product = product;
		this.count = count;
		this.subtotal = subtotal;
	}

	public String getItemid() {
		return this.itemid;
	}

	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Double getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Double subtotal) {
		this.subtotal = subtotal;
	}

}
