package com.sh.domain;
// Generated 2017-10-25 16:26:02 by Hibernate Tools 5.2.5.Final

/**
 * ShopAdmin generated by hbm2java
 */
public class ShopAdmin implements java.io.Serializable {

	private Integer id;
	private String name;
	private String password;

	public ShopAdmin() {
	}

	public ShopAdmin(String name, String password) {
		this.name = name;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "ShopAdmin [id=" + id + ", name=" + name + ", password=" + password + "]";
	}
	
	
}
